import type {
  EnumSchema,
  GeneratedSchema,
  GeneratedSchemas,
  ObjectSchema,
  PropertyType,
  Schema,
} from '@causa/workspace-core';
import { pascalCase } from 'change-case';
import { mkdir, writeFile } from 'fs/promises';
import { dirname, relative } from 'path';
import prettier from 'prettier';

/**
 * The leading comment for any TypeScript source file emitted by the code generators.
 */
export const LEADING_COMMENT =
  'This file was generated by the Causa command line. Do not edit it manually.';

/**
 * The default suffix used to identify constraint classes (e.g. `FooConstraint`).
 */
export const DEFAULT_CONSTRAINT_SUFFIX = 'Constraint';

/**
 * Returns the given property name as it should appear in a TypeScript object literal or class field: bare when it is a
 * valid identifier, JSON-stringified otherwise.
 */
export function propertyKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

/**
 * Strips `suffix` from `name`. Throws when `name` does not end with `suffix`.
 */
export function stripConstraintSuffix(name: string, suffix: string): string {
  if (!name.endsWith(suffix)) {
    throw new Error(`Constraint name '${name}' does not end with '${suffix}'.`);
  }
  return name.slice(0, -suffix.length);
}

/**
 * Returns a shallow copy of `schemas` with each schema's `name` rewritten to a PascalCase, deduplicated identifier
 * suitable for use as a TypeScript top-level export. All emitted names (object classes, constraint aliases + their
 * constraint classes, enums, unions) share a single global namespace. Collisions are resolved by appending `_2`,
 * `_3`, … to the colliding name. For constraint schemas the stripped (alias) form is deduplicated first, then the
 * suffix is reapplied to derive the class name, so both names land in the taken set.
 *
 * Schemas whose path appears in `options.existingSchemas` are rewritten to use the existing name verbatim and are
 * also registered into the taken set, so newly-emitted names never clash with imported ones.
 *
 * Iteration is path-sorted, so the deduplication numbering is stable across runs regardless of the upstream scan order.
 *
 * @param schemas The schema map to normalize.
 * @param options Normalization options.
 * @returns A new schema map with the rewritten names. Schema instances are themselves cloned shallowly; nested
 *   properties / types are shared with the input.
 */
export function assignSchemaNames(
  schemas: Record<string, Schema>,
  options: {
    /**
     * Suffix used to identify constraint classes.
     * Defaults to {@link DEFAULT_CONSTRAINT_SUFFIX}.
     */
    constraintSuffix?: string;

    /**
     * Schemas already emitted by a previous generator run, keyed by absolute schema path.
     */
    existingSchemas?: GeneratedSchemas;
  } = {},
): Record<string, Schema> {
  const constraintSuffix =
    options.constraintSuffix ?? DEFAULT_CONSTRAINT_SUFFIX;
  const existingSchemas = options.existingSchemas ?? {};
  const taken = new Set<string>(
    Object.values(existingSchemas).map((s) => s.name),
  );

  const dedupe = (candidate: string): string => {
    if (!taken.has(candidate)) {
      return candidate;
    }

    for (let i = 2; ; i++) {
      const next = `${candidate}_${i}`;
      if (!taken.has(next)) {
        return next;
      }
    }
  };

  const result: Record<string, Schema> = {};
  const paths = Object.keys(schemas).toSorted((a, b) => a.localeCompare(b));
  for (const path of paths) {
    const schema = schemas[path];
    const existing = existingSchemas[path];
    if (existing) {
      result[path] = { ...schema, name: existing.name };
      continue;
    }

    let name: string;
    if (getConstraintBasePath(schema) !== undefined) {
      const aliasCandidate = pascalCase(
        stripConstraintSuffix(schema.name, constraintSuffix),
      );
      const alias = dedupe(aliasCandidate);
      name = `${alias}${constraintSuffix}`;
      taken.add(alias);
      taken.add(name);
    } else {
      name = dedupe(pascalCase(schema.name));
      taken.add(name);
    }

    result[path] = { ...schema, name };
  }

  return result;
}

/**
 * Returns the path of the schema constrained by `schema` (via `extensions.constraintFor`), or `undefined` when
 * `schema` is not an object schema or carries no `constraintFor` extension.
 */
export function getConstraintBasePath(schema: Schema): string | undefined {
  if (schema.kind !== 'object') {
    return undefined;
  }
  const value = schema.extensions.constraintFor;
  return typeof value === 'string' ? value : undefined;
}

/**
 * Returns the object schema constrained by `schema` (via `extensions.constraintFor`), or `undefined` when `schema` is
 * not a constraint, when the reference is missing from `schemas`, or when the target is not an object schema.
 */
export function getConstraintBaseObject(
  schema: Schema,
  schemas: Record<string, Schema>,
): ObjectSchema | undefined {
  const path = getConstraintBasePath(schema);
  if (path === undefined) {
    return undefined;
  }
  const base = schemas[path];
  return base?.kind === 'object' ? base : undefined;
}

/**
 * Returns the {@link EnumSchema} referenced by a property named `propertyName` on `schema` or on its `constraintFor`
 * base object, or `undefined` when neither has a ref-to-enum property of that name.
 *
 * Used to recover the enum case behind a const-valued constraint property, so generated code can reference the enum
 * member by name rather than emitting the raw value.
 */
export function resolveEnumForObjectProperty(
  schema: ObjectSchema,
  propertyName: string,
  schemas: Record<string, Schema>,
): EnumSchema | undefined {
  for (const obj of [schema, getConstraintBaseObject(schema, schemas)]) {
    const property = obj?.properties.find((p) => p.name === propertyName);
    if (property?.type.kind === 'ref') {
      const target = schemas[property.type.ref];
      if (target?.kind === 'enum') {
        return target;
      }
    }
  }

  return undefined;
}

/**
 * Returns the {@link GeneratedSchema} entry for the given schema path; throws when missing.
 */
export function findModelClass(
  modelClassSchemas: GeneratedSchemas,
  path: string,
): GeneratedSchema {
  const entry = modelClassSchemas[path];
  if (!entry) {
    throw new Error(
      `Schema '${path}' is not present in the model-class generator output.`,
    );
  }
  return entry;
}

/**
 * Returns deduplicated, valid TypeScript enum case names for the given enum schema (preserving source order).
 */
export function enumCaseNames(schema: EnumSchema): string[] {
  const seen = new Map<string, number>();
  return schema.values.map((value) => {
    const base = pascalCase(
      typeof value === 'string' ? value : `const_${value}`,
    );
    const safe = /^[A-Za-z_$]/.test(base) ? base : `_${base}`;
    const count = seen.get(safe) ?? 0;
    seen.set(safe, count + 1);
    return count === 0 ? safe : `${safe}_${count + 1}`;
  });
}

/**
 * Returns the TypeScript enum case name corresponding to the given raw value, or `undefined` when the value is absent
 * from the enum.
 */
export function findEnumCaseName(
  schema: EnumSchema,
  value: unknown,
): string | undefined {
  const index = (schema.values as unknown[]).indexOf(value);
  if (index < 0) {
    return undefined;
  }
  return enumCaseNames(schema)[index];
}

/**
 * Recursively collects the schema paths referenced by the given property type into `out`.
 *
 * @param type Type to walk.
 * @param out Set to accumulate refs into.
 * @param accept Optional predicate; refs for which it returns `false` are skipped (but the walk continues into nested
 *   types). Defaults to accepting every ref.
 */
export function collectRefs(
  type: PropertyType,
  out: Set<string>,
  accept: (ref: string) => boolean = () => true,
): void {
  switch (type.kind) {
    case 'ref':
      if (accept(type.ref)) {
        out.add(type.ref);
      }
      return;
    case 'array':
      collectRefs(type.items, out, accept);
      return;
    case 'map':
      if (type.items !== 'any') {
        collectRefs(type.items, out, accept);
      }
      return;
    default:
      return;
  }
}

/**
 * Kahn-style topological sort with deterministic tiebreak (alphabetical by `nameOf`, then by node id).
 *
 * @param nodes The nodes (schema paths) to sort.
 * @param dependenciesOf Returns the nodes that must be emitted before `node`. Dependencies outside `nodes` are ignored.
 * @param nameOf Returns the display name used for the alphabetical tiebreak.
 * @returns The nodes in dependency-respecting order.
 * @throws When the dependency graph contains a cycle.
 */
export function topologicalSort(
  nodes: string[],
  dependenciesOf: (node: string) => Iterable<string>,
  nameOf: (node: string) => string,
): string[] {
  const nodeSet = new Set(nodes);
  const inDegree = new Map<string, number>();
  const dependents = new Map<string, string[]>();
  for (const node of nodes) {
    inDegree.set(node, 0);
    dependents.set(node, []);
  }

  for (const node of nodes) {
    for (const dep of dependenciesOf(node)) {
      if (!nodeSet.has(dep) || dep === node) {
        continue;
      }
      inDegree.set(node, (inDegree.get(node) ?? 0) + 1);
      dependents.get(dep)?.push(node);
    }
  }

  const ready = nodes.filter((n) => (inDegree.get(n) ?? 0) === 0);
  const result: string[] = [];
  while (ready.length > 0) {
    ready.sort(
      (a, b) => nameOf(a).localeCompare(nameOf(b)) || a.localeCompare(b),
    );
    const next = ready.shift()!;
    result.push(next);
    for (const dependent of dependents.get(next) ?? []) {
      const remaining = (inDegree.get(dependent) ?? 0) - 1;
      inDegree.set(dependent, remaining);
      if (remaining === 0) {
        ready.push(dependent);
      }
    }
  }

  if (result.length !== nodes.length) {
    throw new Error('Cycle detected in schema dependency graph.');
  }
  return result;
}

/**
 * Returns the local alias under which a symbol imported from an external module is exposed in generated code.
 *
 * @param module The external module specifier (e.g. `@causa/runtime`).
 * @param symbol The exported symbol to import.
 * @returns The local alias (e.g. `_CausaRuntimeIsNullable`).
 */
export function externalSymbolAlias(module: string, symbol: string): string {
  const segments = module.replace(/^@/, '').split('/');
  const base = module.startsWith('@')
    ? segments.slice(0, 2).join('-')
    : segments[0];
  return `_${pascalCase(`${base}-${symbol}`)}`;
}

/**
 * Returns the import specifier (the text inside the `import { ... }` braces) that binds an external `symbol` to its
 * {@link externalSymbolAlias}.
 *
 * @param module The external module specifier (e.g. `@causa/runtime`).
 * @param symbol The exported symbol to import.
 * @param isType Whether to emit a type-only import.
 * @returns The import specifier text (e.g. `type IsNullable as _CausaRuntimeIsNullable`).
 */
export function externalImportSpec(
  module: string,
  symbol: string,
  isType = false,
): string {
  return `${isType ? 'type ' : ''}${symbol} as ${externalSymbolAlias(module, symbol)}`;
}

/**
 * Merges the given symbol additions into `target` in place. Keys are module specifiers or absolute file paths.
 */
export function mergeImports(
  target: Record<string, Set<string>>,
  additions: Record<string, string[]>,
): void {
  for (const [path, symbols] of Object.entries(additions)) {
    const existing = target[path];
    if (existing) {
      for (const s of symbols) {
        existing.add(s);
      }
    } else {
      target[path] = new Set(symbols);
    }
  }
}

/**
 * Renders the source for an imports dictionary, sorted: module specifiers first (alphabetically), then absolute paths
 * converted to relative `./...js` imports. Type-only imports are deduplicated when their value-import counterpart is
 * also present.
 *
 * @param imports Imports dictionary.
 * @param outputPath Absolute path of the file the imports are being emitted into (used to compute relative paths).
 */
export function renderImports(
  imports: Record<string, Set<string>>,
  outputPath: string,
): string {
  const entries = Object.entries(imports);
  if (entries.length === 0) {
    return '';
  }

  const outputDir = dirname(outputPath);
  const sorted = entries
    .map(([path, symbols]) => {
      let specifier = path;
      if (path.startsWith('/')) {
        specifier = relative(outputDir, path);
        if (!specifier.startsWith('.')) {
          specifier = `./${specifier}`;
        }
        specifier = specifier.replace(/\.ts$/, '.js');
      }
      return { path, symbols, specifier };
    })
    .toSorted(
      (a, b) =>
        Number(a.path.startsWith('/')) - Number(b.path.startsWith('/')) ||
        a.specifier.localeCompare(b.specifier),
    );

  const lines: string[] = [];
  for (const { specifier, symbols } of sorted) {
    if (symbols.size === 0) {
      lines.push(`import '${specifier}';`);
      continue;
    }
    const symbolsList = [...symbols]
      .filter((s) => !s.startsWith('type ') || !symbols.has(s.slice(5)))
      .toSorted()
      .join(', ');
    lines.push(`import { ${symbolsList} } from '${specifier}';`);
  }
  return lines.join('\n');
}

/**
 * Formats the given source with `prettier` and writes it to `outputPath`, creating the parent directory if needed.
 */
export async function formatAndWriteTypeScript(
  outputPath: string,
  source: string,
): Promise<void> {
  const prettierConfig = await prettier.resolveConfig(outputPath);
  const formatted = await prettier.format(source, {
    parser: 'typescript',
    ...prettierConfig,
  });
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, formatted);
}

/**
 * Base class for TypeScript code generators. Owns:
 * - the imports dictionary and its rendering,
 * - the leading comment + prettier formatting + file writing.
 *
 * Subclasses build the body string and call {@link renderFile} to finish.
 */
export abstract class BaseTypeScriptCodeGenerator {
  /**
   * Schemas successfully emitted, indexed by their source path. Populated by subclasses as they emit each schema.
   */
  readonly generatedSchemas: GeneratedSchemas = {};

  /**
   * Imports collected while emitting. Keys are module specifiers or absolute file paths; values are the symbols to
   * import.
   */
  private readonly imports: Record<string, Set<string>> = {};

  /**
   * @param outputPath Absolute path of the file the rendered source will be written to.
   */
  protected constructor(readonly outputPath: string) {}

  /**
   * Merges the given imports into the generator's imports dictionary.
   */
  protected addImports(imports: Record<string, string[]>): void {
    mergeImports(this.imports, imports);
  }

  /**
   * Records an aliased import for `symbol` from the external module `module` and returns the local alias to reference
   * it by in generated code. Use this for every symbol pulled from a package so it cannot clash with schema names or
   * with symbols from other external modules.
   *
   * @param module The external module specifier (e.g. `@causa/runtime`).
   * @param symbol The exported symbol to import.
   * @param options Additional options.
   * @returns The alias to use in generated source.
   */
  protected importExternal(
    module: string,
    symbol: string,
    options: {
      /**
       * Whether to emit a type-only import.
       */
      type?: boolean;
    } = {},
  ): string {
    this.addImports({
      [module]: [externalImportSpec(module, symbol, options.type)],
    });
    return externalSymbolAlias(module, symbol);
  }

  /**
   * Renders the collected imports as a source block (see {@link renderImports}).
   */
  protected emitImports(): string {
    return renderImports(this.imports, this.outputPath);
  }

  /**
   * Prepends the leading comment + imports to the given body, formats the result with `prettier`, and writes it to
   * {@link outputPath}.
   */
  protected async renderFile(body: string): Promise<void> {
    const source = [
      ...LEADING_COMMENT.split('\n').map((l) => `// ${l}`),
      '',
      this.emitImports(),
      '',
      body,
    ].join('\n');
    await formatAndWriteTypeScript(this.outputPath, source);
  }
}
