// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing, IsNullable } from '@causa/workspace/validation';
import { Type } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsIn,
  IsObject,
  IsString,
  ValidateNested,
} from 'class-validator';

/**
 * Configuration for a custom code generator.
 */
export class CustomCodeGenerator {
  constructor(init: CustomCodeGenerator) {
    Object.assign(this, init);
  }

  /**
   * The name of the generator to run.
   */
  @IsString()
  readonly generator!: string;

  [key: string]: any;
}

/**
 * The minimum severity level of vulnerabilities to fail the check.
 */
export enum JavaScriptDependenciesCheckLevel {
  Low = 'low',
  Moderate = 'moderate',
  High = 'high',
  Critical = 'critical',
}

/**
 * Configuration used when checking dependencies for vulnerabilities.
 */
export class JavaScriptDependenciesCheck {
  constructor(init: JavaScriptDependenciesCheck) {
    Object.assign(this, init);
  }

  /**
   * Whether to ignore vulnerabilities in dev dependencies.
   */
  @AllowMissing()
  @IsBoolean()
  readonly skipDev?: boolean;

  /**
   * The minimum severity level of vulnerabilities to fail the check.
   */
  @AllowMissing()
  @IsIn(['low', 'moderate', 'high', 'critical'])
  readonly level?: JavaScriptDependenciesCheckLevel;

  /**
   * A list of vulnerabilities to allow.
   * See: https://github.com/IBM/audit-ci#allowlisting
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly allowlist?: string[];

  [key: string]: any;
}

export enum JavaScriptDependenciesUpdatePackageTarget {
  Latest = 'latest',
  Newest = 'newest',
  Greatest = 'greatest',
  Minor = 'minor',
  Patch = 'patch',
  Semver = 'semver',
}

/**
 * The default target version when updating dependencies.
 * Defaults to `latest`.
 */
export enum JavaScriptDependenciesUpdateTarget {
  Latest = 'latest',
  Newest = 'newest',
  Greatest = 'greatest',
  Minor = 'minor',
  Patch = 'patch',
}

/**
 * Configuration related to the update of dependencies.
 */
export class JavaScriptDependenciesUpdate {
  constructor(init: JavaScriptDependenciesUpdate) {
    Object.assign(this, init);
  }

  /**
   * The default target version when updating dependencies.
   * Defaults to `latest`.
   */
  @AllowMissing()
  @IsIn(['latest', 'newest', 'greatest', 'minor', 'patch'])
  readonly defaultTarget?: JavaScriptDependenciesUpdateTarget;

  /**
   * The target version for specific packages when updating dependencies.
   * Keys are package names, values are target versions.
   */
  @AllowMissing()
  @IsObject()
  readonly packageTargets?: Record<
    string,
    JavaScriptDependenciesUpdatePackageTarget
  >;

  [key: string]: any;
}

/**
 * Configuration related to JavaScript dependencies.
 */
export class JavaScriptDependencies {
  constructor(init: JavaScriptDependencies) {
    Object.assign(this, init);
  }

  /**
   * Configuration used when checking dependencies for vulnerabilities.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => JavaScriptDependenciesCheck)
  @ValidateNested()
  readonly check?: JavaScriptDependenciesCheck;

  /**
   * Configuration related to the update of dependencies.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => JavaScriptDependenciesUpdate)
  @ValidateNested()
  readonly update?: JavaScriptDependenciesUpdate;

  [key: string]: any;
}

/**
 * A JavaScript project.
 */
export enum JavaScriptLanguage {
  Javascript = 'javascript',
}

/**
 * Configuration related to Node.
 */
export class JavaScriptNode {
  constructor(init: JavaScriptNode) {
    Object.assign(this, init);
  }

  /**
   * The Node version to use, for example when building Docker images.
   * Can be a semver version, or `latest`.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;

  [key: string]: any;
}

/**
 * The NestJS application module used to generate the OpenAPI specification.
 */
export class JavaScriptOpenApiApplicationModule {
  constructor(init: JavaScriptOpenApiApplicationModule) {
    Object.assign(this, init);
  }

  /**
   * The JavaScript source file containing the NestJS application module.
   * This path is relative to the Docker container's `/app` directory (the working directory), which is usually also the project's root.
   */
  @IsString()
  readonly sourceFile!: string;

  /**
   * The name of the JavaScript class for NestJS application module.
   * It should be exported from the source file.
   */
  @IsString()
  readonly name!: string;

  [key: string]: any;
}

/**
 * Configuration related to the generation of OpenAPI specifications.
 */
export class JavaScriptOpenApi {
  constructor(init: JavaScriptOpenApi) {
    Object.assign(this, init);
  }

  /**
   * Defines the location of the NestJS application module when generating the OpenAPI specification for a `serviceContainer` project.
   * If this is not set or `null`, the OpenAPI specification will not be generated.
   */
  @AllowMissing()
  @IsNullable()
  @IsObject()
  @Type(() => JavaScriptOpenApiApplicationModule)
  @ValidateNested()
  readonly applicationModule?: JavaScriptOpenApiApplicationModule | null;

  [key: string]: any;
}

export type TemplateString = string;

/**
 * Configuration for running npm commands.
 */
export class Npm {
  constructor(init: Npm) {
    Object.assign(this, init);
  }

  /**
   * Environment variables to set when running npm.
   * Supports formatting.
   */
  @AllowMissing()
  @IsObject()
  readonly environment?: Record<string, TemplateString>;

  /**
   * The version of npm to use.
   * Can be a semver version, or `latest`.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;

  /**
   * The destination directory for built packages, relative to the project's root.
   * This is used when building JavaScript / TypeScript package artefacts.
   */
  @AllowMissing()
  @IsString()
  readonly packDestination?: string;

  /**
   * The sandbox profiles to use when running npm commands.
   * Keys are npm command names (e.g. `build`, `ci`), or `run <script>` for npm scripts.
   * Values are sandbox profile keys defined under the `causa.sandboxes` configuration.
   * The `default` key is used when no command-specific sandbox matches.
   * If no command matches and no default is set, the command is not sandboxed.
   */
  @AllowMissing()
  @IsObject()
  readonly sandbox?: Record<string, string>;

  [key: string]: any;
}

/**
 * Configuration for JavaScript-related tools, usually for TypeScript projects.
 */
export class JavaScript {
  constructor(init: JavaScript) {
    Object.assign(this, init);
  }

  /**
   * Configuration for running npm commands.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Npm)
  @ValidateNested()
  readonly npm?: Npm;

  /**
   * Configuration related to Node.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => JavaScriptNode)
  @ValidateNested()
  readonly node?: JavaScriptNode;

  /**
   * Configuration related to JavaScript dependencies.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => JavaScriptDependencies)
  @ValidateNested()
  readonly dependencies?: JavaScriptDependencies;

  /**
   * Configuration related to the generation of OpenAPI specifications.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => JavaScriptOpenApi)
  @ValidateNested()
  readonly openApi?: JavaScriptOpenApi;

  [key: string]: any;
}

/**
 * Configuration for TypeScript and JavaScript projects.
 */
export class TypeScriptConfiguration {
  constructor(init: TypeScriptConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for JavaScript-related tools, usually for TypeScript projects.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => JavaScript)
  @ValidateNested()
  readonly javascript?: JavaScript;

  [key: string]: any;
}

/**
 * A TypeScript project.
 */
export enum TypeScriptLanguage {
  Typescript = 'typescript',
}

export type Language = string | JavaScriptLanguage | TypeScriptLanguage;

/**
 * The name of the generator to run.
 */
export enum TypeScriptModelClassCodeGeneratorName {
  TypescriptModelClass = 'typescriptModelClass',
}

/**
 * Configuration for the TypeScript model class code generator.
 */
export class TypeScriptModelClassCodeGenerator {
  constructor(init: TypeScriptModelClassCodeGenerator) {
    Object.assign(this, init);
  }

  /**
   * The name of the generator to run.
   */
  @IsIn(['typescriptModelClass'])
  readonly generator!: TypeScriptModelClassCodeGeneratorName;

  /**
   * The path, relative to the project root, to the file where generated model classes should be written.
   */
  @IsString()
  readonly output!: string;

  /**
   * A list of glob patterns to find schema definition files.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly globs?: string[];

  /**
   * A list of nested schemas to include.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly nestedSchemas?: string[];

  /**
   * Whether to include event topic schemas referenced in the project.
   */
  @AllowMissing()
  @IsBoolean()
  readonly includeEvents?: boolean;

  /**
   * Whether to include full JSON Schema references.
   */
  @AllowMissing()
  @IsBoolean()
  readonly includeFullReferences?: boolean;

  [key: string]: any;
}

/**
 * The name of the generator to run.
 */
export enum TypeScriptNestjsControllerCodeGeneratorName {
  TypescriptNestjsController = 'typescriptNestjsController',
}

/**
 * Configuration for the TypeScript NestJS controller code generator.
 */
export class TypeScriptNestjsControllerCodeGenerator {
  constructor(init: TypeScriptNestjsControllerCodeGenerator) {
    Object.assign(this, init);
  }

  /**
   * The name of the generator to run.
   */
  @IsIn(['typescriptNestjsController'])
  readonly generator!: TypeScriptNestjsControllerCodeGeneratorName;

  /**
   * The path, relative to the project root, to the directory where generated controllers should be written.
   */
  @IsString()
  readonly output!: string;

  /**
   * A list of glob patterns to find OpenAPI specification files.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly globs?: string[];

  [key: string]: any;
}

export class TypeScriptProject {
  constructor(init: TypeScriptProject) {
    Object.assign(this, init);
  }

  @AllowMissing()
  readonly language?: Language;

  [key: string]: any;
}

/**
 * Refinement of the project configuration with known JavaScript and TypeScript languages.
 */
export class TypeScriptProjectConfiguration {
  constructor(init: TypeScriptProjectConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsObject()
  @Type(() => TypeScriptProject)
  @ValidateNested()
  readonly project?: TypeScriptProject;

  [key: string]: any;
}

/**
 * The name of the generator to run.
 */
export enum TypeScriptTestExpectationCodeGeneratorName {
  TypescriptTestExpectation = 'typescriptTestExpectation',
}

/**
 * Configuration for the TypeScript test expectation code generator.
 */
export class TypeScriptTestExpectationCodeGenerator {
  constructor(init: TypeScriptTestExpectationCodeGenerator) {
    Object.assign(this, init);
  }

  /**
   * The name of the generator to run.
   */
  @IsIn(['typescriptTestExpectation'])
  readonly generator!: TypeScriptTestExpectationCodeGeneratorName;

  /**
   * The path, relative to the project root, to the file where generated test expectations should be written.
   */
  @IsString()
  readonly output!: string;

  /**
   * A list of glob patterns to find schema definition files.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly globs?: string[];

  /**
   * A list of nested schemas to include.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly nestedSchemas?: string[];

  /**
   * Whether to include event topic schemas referenced in the project.
   */
  @AllowMissing()
  @IsBoolean()
  readonly includeEvents?: boolean;

  /**
   * Whether to include full JSON Schema references.
   */
  @AllowMissing()
  @IsBoolean()
  readonly includeFullReferences?: boolean;

  /**
   * A list of glob patterns to filter which schemas should generate entity expectation functions.
   * Patterns are resolved relative to the project root.
   * If not specified, expectations are generated for all types.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly entitiesGlobs?: string[];

  [key: string]: any;
}

/**
 * The name of the generator to run.
 */
export enum TypeScriptTestObjectCodeGeneratorName {
  TypescriptTestObject = 'typescriptTestObject',
}

/**
 * Configuration for the TypeScript test object code generator.
 */
export class TypeScriptTestObjectCodeGenerator {
  constructor(init: TypeScriptTestObjectCodeGenerator) {
    Object.assign(this, init);
  }

  /**
   * The name of the generator to run.
   */
  @IsIn(['typescriptTestObject'])
  readonly generator!: TypeScriptTestObjectCodeGeneratorName;

  /**
   * The path, relative to the project root, to the file where generated test objects should be written.
   */
  @IsString()
  readonly output!: string;

  /**
   * A list of glob patterns to find schema definition files.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly globs?: string[];

  /**
   * A list of nested schemas to include.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly nestedSchemas?: string[];

  /**
   * Whether to include event topic schemas referenced in the project.
   */
  @AllowMissing()
  @IsBoolean()
  readonly includeEvents?: boolean;

  /**
   * Whether to include full JSON Schema references.
   */
  @AllowMissing()
  @IsBoolean()
  readonly includeFullReferences?: boolean;

  [key: string]: any;
}

export type CodeGenerator =
  | CustomCodeGenerator
  | TypeScriptModelClassCodeGenerator
  | TypeScriptTestObjectCodeGenerator
  | TypeScriptTestExpectationCodeGenerator
  | TypeScriptNestjsControllerCodeGenerator;

export class TypeScriptModel {
  constructor(init: TypeScriptModel) {
    Object.assign(this, init);
  }

  /**
   * The suffix that should be present on constraint types. It will be removed during code generation.
   * Defaults to `Constraint`.
   * Applies to every TypeScript model code generator.
   */
  @AllowMissing()
  @IsString()
  readonly constraintSuffix?: string;

  @AllowMissing()
  @IsArray()
  readonly codeGenerators?: CodeGenerator[];

  [key: string]: any;
}

/**
 * Configuration for model code generators provided by the TypeScript module.
 */
export class TypeScriptModelConfiguration {
  constructor(init: TypeScriptModelConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsObject()
  @Type(() => TypeScriptModel)
  @ValidateNested()
  readonly model?: TypeScriptModel;

  [key: string]: any;
}
