// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing, IsNullable } from '@causa/workspace/validation';
import { IsArray, IsBoolean, IsIn, IsObject, IsString } from 'class-validator';

/**
 * Configuration for the TypeScript NestJS controller code generator.
 */
export class TypeScriptCodeGenerator {
  constructor(init: TypeScriptCodeGenerator) {
    Object.assign(this, init);
  }

  /**
   * The name of the generator to run.
   */
  @IsString()
  readonly generator!: string;

  /**
   * The suffix that should be present on constraint types. It will be removed during code generation.
   * Defaults to `Constraint`.
   */
  @AllowMissing()
  @IsString()
  readonly constraintSuffix?: string;

  /**
   * A list of glob patterns to find schema definition files.
   *
   * A list of glob patterns to find OpenAPI specification files.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly globs?: string[];

  /**
   * Whether to include event topic schemas referenced in the project.
   */
  @AllowMissing()
  @IsBoolean()
  readonly includeEvents?: boolean;

  /**
   * Whether to include full JSON Schema references.
   */
  @AllowMissing()
  @IsBoolean()
  readonly includeFullReferences?: boolean;

  /**
   * A list of nested schemas to include.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly nestedSchemas?: string[];

  /**
   * The path, relative to the project root, to the file where generated model classes should be written.
   *
   * The path, relative to the project root, to the file where generated test objects should be written.
   *
   * The path, relative to the project root, to the file where generated test expectations should be written.
   *
   * The path, relative to the project root, to the directory where generated controllers should be written.
   */
  @AllowMissing()
  @IsString()
  readonly output?: string;

  /**
   * A list of glob patterns to filter which schemas should generate entity expectation functions.
   * Patterns are resolved relative to the project root.
   * If not specified, expectations are generated for all types.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly entitiesGlobs?: string[];
  [property: string]: any;
}

export class Model {
  constructor(init: Model) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsArray()
  readonly codeGenerators?: TypeScriptCodeGenerator[];
  [property: string]: any;
}

/**
 * Configuration for model code generators provided by the TypeScript module.
 */
export class ModelConfiguration {
  constructor(init: ModelConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  readonly model?: Model;
  [property: string]: any;
}

export class Project {
  constructor(init: Project) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsString()
  readonly language?: string;
  [property: string]: any;
}

/**
 * Refinement of the project configuration with known JavaScript and TypeScript languages.
 */
export class TypeScriptProjectConfiguration {
  constructor(init: TypeScriptProjectConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  readonly project?: Project;
  [property: string]: any;
}

/**
 * The minimum severity level of vulnerabilities to fail the check.
 */
export enum JavaScriptDependenciesCheckLevel {
  Critical = 'critical',
  High = 'high',
  Low = 'low',
  Moderate = 'moderate',
}

/**
 * Configuration used when checking dependencies for vulnerabilities.
 */
export class JavaScriptDependenciesCheck {
  constructor(init: JavaScriptDependenciesCheck) {
    Object.assign(this, init);
  }

  /**
   * A list of vulnerabilities to allow.
   * See: https://github.com/IBM/audit-ci#allowlisting
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly allowlist?: string[];

  /**
   * The minimum severity level of vulnerabilities to fail the check.
   */
  @AllowMissing()
  @IsIn(['low', 'moderate', 'high', 'critical'])
  readonly level?: JavaScriptDependenciesCheckLevel;

  /**
   * Whether to ignore vulnerabilities in dev dependencies.
   */
  @AllowMissing()
  @IsBoolean()
  readonly skipDev?: boolean;
  [property: string]: any;
}

/**
 * The default target version when updating dependencies.
 * Defaults to `latest`.
 */
export enum JavaScriptDependenciesUpdateTarget {
  Greatest = 'greatest',
  Latest = 'latest',
  Minor = 'minor',
  Newest = 'newest',
  Patch = 'patch',
}

/**
 * Configuration related to the update of dependencies.
 */
export class JavaScriptDependenciesUpdate {
  constructor(init: JavaScriptDependenciesUpdate) {
    Object.assign(this, init);
  }

  /**
   * The default target version when updating dependencies.
   * Defaults to `latest`.
   */
  @AllowMissing()
  @IsIn(['latest', 'newest', 'greatest', 'minor', 'patch'])
  readonly defaultTarget?: JavaScriptDependenciesUpdateTarget;

  /**
   * The target version for specific packages when updating dependencies.
   * Keys are package names, values are target versions.
   */
  @AllowMissing()
  @IsObject()
  readonly packageTargets?: {
    [key: string]: JavaScriptDependenciesUpdateTarget;
  };
  [property: string]: any;
}

/**
 * Configuration related to JavaScript dependencies.
 */
export class JavaScriptDependencies {
  constructor(init: JavaScriptDependencies) {
    Object.assign(this, init);
  }

  /**
   * Configuration used when checking dependencies for vulnerabilities.
   */
  @AllowMissing()
  readonly check?: JavaScriptDependenciesCheck;

  /**
   * Configuration related to the update of dependencies.
   */
  @AllowMissing()
  readonly update?: JavaScriptDependenciesUpdate;
  [property: string]: any;
}

/**
 * Configuration related to Node.
 */
export class JavaScriptNode {
  constructor(init: JavaScriptNode) {
    Object.assign(this, init);
  }

  /**
   * The Node version to use, for example when building Docker images.
   * Can be a semver version, or `latest`.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;
  [property: string]: any;
}

/**
 * Configuration for running npm commands.
 */
export class Npm {
  constructor(init: Npm) {
    Object.assign(this, init);
  }

  /**
   * Environment variables to set when running npm.
   * Supports formatting.
   */
  @AllowMissing()
  @IsObject()
  readonly environment?: { [key: string]: string };

  /**
   * The destination directory for built packages, relative to the project's root.
   * This is used when building JavaScript / TypeScript package artefacts.
   */
  @AllowMissing()
  @IsString()
  readonly packDestination?: string;

  /**
   * The version of npm to use.
   * Can be a semver version, or `latest`.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;
  [property: string]: any;
}

/**
 * The NestJS application module used to generate the OpenAPI specification.
 */
export class JavaScriptOpenAPIApplicationModule {
  constructor(init: JavaScriptOpenAPIApplicationModule) {
    Object.assign(this, init);
  }

  /**
   * The name of the JavaScript class for NestJS application module.
   * It should be exported from the source file.
   */
  @IsString()
  readonly name!: string;

  /**
   * The JavaScript source file containing the NestJS application module.
   * This path is relative to the Docker container's `/app` directory (the working directory), which is usually also the project's root.
   */
  @IsString()
  readonly sourceFile!: string;
  [property: string]: any;
}

/**
 * Configuration related to the generation of OpenAPI specifications.
 */
export class JavaScriptOpenAPI {
  constructor(init: JavaScriptOpenAPI) {
    Object.assign(this, init);
  }

  /**
   * Defines the location of the NestJS application module when generating the OpenAPI specification for a `serviceContainer` project.
   * If this is not set or `null`, the OpenAPI specification will not be generated.
   */
  @IsNullable()
  @AllowMissing()
  readonly applicationModule?: null | JavaScriptOpenAPIApplicationModule;
  [property: string]: any;
}

/**
 * Configuration for JavaScript-related tools, usually for TypeScript projects.
 */
export class JavaScript {
  constructor(init: JavaScript) {
    Object.assign(this, init);
  }

  /**
   * Configuration related to JavaScript dependencies.
   */
  @AllowMissing()
  readonly dependencies?: JavaScriptDependencies;

  /**
   * Configuration related to Node.
   */
  @AllowMissing()
  readonly node?: JavaScriptNode;

  /**
   * Configuration for running npm commands.
   */
  @AllowMissing()
  readonly npm?: Npm;

  /**
   * Configuration related to the generation of OpenAPI specifications.
   */
  @AllowMissing()
  readonly openApi?: JavaScriptOpenAPI;
  [property: string]: any;
}

/**
 * Configuration for TypeScript and JavaScript projects.
 */
export class TypeScriptConfiguration {
  constructor(init: TypeScriptConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for JavaScript-related tools, usually for TypeScript projects.
   */
  @AllowMissing()
  readonly javascript?: JavaScript;
  [property: string]: any;
}
