import type {
  EnumSchema,
  GeneratedSchemas,
  ObjectSchema,
  Property,
  PropertyType,
  Schema,
  UnionSchema,
} from '@causa/workspace-core';
import { pascalCase } from 'change-case';
import { mkdir, writeFile } from 'fs/promises';
import { dirname, relative } from 'path';
import prettier from 'prettier';

/**
 * A decorator that can be added to a class or property.
 */
export type TypeScriptDecorator = {
  /**
   * The source code for the decorator.
   */
  source: string;

  /**
   * The imports that are required for the decorator. Keys are modules or absolute file paths; values are the names of
   * the symbols to import.
   */
  imports: Record<string, string[]>;
};

/**
 * The default suffix used to identify constraint classes (e.g. `FooConstraint`).
 */
const DEFAULT_CONSTRAINT_SUFFIX = 'Constraint';

/**
 * The default leading comment for the generated file.
 */
const DEFAULT_LEADING_COMMENT =
  'This file was generated by the Causa command line. Do not edit it manually.';

/**
 * Decorators to add to a single object schema and its properties.
 */
export type ModelClassSchemaDecorators = {
  /**
   * Decorators added to the class.
   */
  class: TypeScriptDecorator[];

  /**
   * Decorators added to each property, keyed by the JSON property name.
   */
  properties: Record<string, TypeScriptDecorator[]>;
};

/**
 * Options for {@link TypeScriptModelClassGenerator}.
 */
export type TypeScriptModelClassGeneratorOptions = Partial<
  Pick<
    TypeScriptModelClassGenerator,
    'constraintSuffix' | 'decorators' | 'existingSchemas'
  >
>;

/**
 * Generates TypeScript model classes from a set of {@link Schema}s and writes the formatted output to disk.
 *
 * The generator owns:
 * - dependency-order emission (topological sort with alphabetical tie-break),
 * - class / enum / union / constraint-alias emission,
 * - imports collection,
 * - prettier formatting and file writing.
 *
 * Decorators must be pre-computed by the caller and passed via {@link decorators}.
 */
export class TypeScriptModelClassGenerator {
  /**
   * Schemas successfully emitted, indexed by their source path.
   */
  readonly generatedSchemas: GeneratedSchemas = {};

  /**
   * Imports collected while emitting. Keys are module specifiers or absolute file paths; values are the symbols to
   * import.
   */
  private readonly imports: Record<string, Set<string>> = {};

  /**
   * The alias name used for constraint classes (suffix stripped), keyed by schema path.
   */
  private readonly constraintAliasNames: Record<string, string> = {};

  /**
   * The TypeScript identifier used for each schema (PascalCased), keyed by schema path.
   */
  private readonly classNames: Record<string, string> = {};

  /**
   * The suffix used to identify constraint classes.
   * Defaults to `Constraint`.
   */
  readonly constraintSuffix: string;

  /**
   * Pre-computed decorators for each object schema and its properties, keyed by schema path.
   */
  readonly decorators: Record<string, ModelClassSchemaDecorators>;

  /**
   * Schemas that were already emitted by a previous generator run, keyed by absolute schema path. Paths in this map
   * are not re-emitted; references to them resolve to the {@link GeneratedSchema.name} and add an import from
   * {@link GeneratedSchema.file}. The full {@link Schema} for these paths should still be present in `schemas` so
   * decorator builders can introspect their kind.
   */
  readonly existingSchemas: GeneratedSchemas;

  /**
   * Creates a new generator.
   *
   * @param outputPath Absolute path of the file the rendered source will be written to.
   * @param schemas The schemas to render, indexed by their absolute source path.
   * @param options Options.
   */
  constructor(
    readonly outputPath: string,
    readonly schemas: Record<string, Schema>,
    readonly options: TypeScriptModelClassGeneratorOptions = {},
  ) {
    this.constraintSuffix =
      options.constraintSuffix ?? DEFAULT_CONSTRAINT_SUFFIX;
    this.decorators = options.decorators ?? {};
    this.existingSchemas = options.existingSchemas ?? {};

    for (const [path, schema] of Object.entries(schemas)) {
      if (this.existingSchemas[path]) {
        continue;
      }

      this.classNames[path] = pascalCase(schema.name);

      if (this.getBasePathForConstraintSchema(schema) !== undefined) {
        this.constraintAliasNames[path] = pascalCase(
          this.stripConstraintSuffix(schema.name),
        );
      }
    }
    for (const [path, existing] of Object.entries(this.existingSchemas)) {
      this.classNames[path] = existing.name;
    }
  }

  /**
   * Renders all schemas, formats the output with prettier, and writes it to {@link outputPath}.
   * Populates {@link generatedSchemas}.
   */
  async generate(): Promise<void> {
    const ordered = this.topologicalSort();

    const schemasLines: string[] = [];
    for (const schema of ordered) {
      schemasLines.push(this.emitSchema(schema));
    }
    const importsBlock = this.emitImports();

    const lines = [
      ...DEFAULT_LEADING_COMMENT.split('\n').map((l) => `// ${l}`),
      '',
      importsBlock,
      '',
      schemasLines.join('\n\n'),
    ];

    await this.writeFile(lines.join('\n'));
  }

  /**
   * Formats the given source code with `prettier` and writes it to {@link outputPath}, creating the parent directory
   * if needed.
   */
  private async writeFile(source: string): Promise<void> {
    const prettierConfig = await prettier.resolveConfig(this.outputPath);

    const formattedOutput = await prettier.format(source, {
      parser: 'typescript',
      ...prettierConfig,
    });

    await mkdir(dirname(this.outputPath), { recursive: true });
    await writeFile(this.outputPath, formattedOutput);
  }

  /**
   * Returns the TypeScript identifier used to reference the given schema. Throws when the schema was not registered
   * with the generator at construction time.
   */
  private getSchemaName(schema: Schema): string {
    const name = this.classNames[schema.path];
    if (name === undefined) {
      throw new Error(`No registered class name for schema '${schema.path}'.`);
    }
    return name;
  }

  /**
   * Returns the absolute path of the schema that the given schema is a constraint for, if any.
   */
  private getBasePathForConstraintSchema(schema: Schema): string | undefined {
    if (schema.kind !== 'object') {
      return undefined;
    }
    const value = schema.extensions.constraintFor;
    return typeof value === 'string' ? value : undefined;
  }

  /**
   * Strips the constraint suffix from the given class name.
   */
  private stripConstraintSuffix(name: string): string {
    if (!name.endsWith(this.constraintSuffix)) {
      throw new Error(
        `Constraint name '${name}' does not end with '${this.constraintSuffix}'.`,
      );
    }
    return name.slice(0, -this.constraintSuffix.length);
  }

  /**
   * Returns every other schema path that the given schema depends on (must be emitted before).
   *
   * Constraint classes do NOT depend on their `constraintFor` base, since the type alias may forward-reference it.
   */
  private dependenciesOf(schema: Schema): string[] {
    const deps = new Set<string>();
    if (schema.kind === 'object') {
      for (const property of schema.properties) {
        this.collectRefs(property.type, deps);
        const enumHint = property.extensions.enumHint;
        if (typeof enumHint === 'string') {
          deps.add(enumHint);
        }
      }
    } else if (schema.kind === 'union') {
      for (const t of schema.types) {
        this.collectRefs(t, deps);
      }
    }
    deps.delete(schema.path);
    return [...deps];
  }

  /**
   * Recursively collects every absolute schema path referenced by the given property type.
   */
  private collectRefs(type: PropertyType, out: Set<string>): void {
    switch (type.kind) {
      case 'ref':
        out.add(type.ref);
        return;
      case 'array':
        this.collectRefs(type.items, out);
        return;
      case 'map':
        if (type.items !== 'any') {
          this.collectRefs(type.items, out);
        }
        return;
      default:
        return;
    }
  }

  /**
   * Topologically sorts the schemas so that dependencies are emitted before their dependents. Ties are broken by
   * emit-name (alphabetical), then by path for determinism.
   */
  private topologicalSort(): Schema[] {
    const paths = Object.keys(this.schemas).filter(
      (p) => !this.existingSchemas[p],
    );
    const inDegree = new Map<string, number>();
    const dependents = new Map<string, string[]>();
    for (const path of paths) {
      inDegree.set(path, 0);
      dependents.set(path, []);
    }

    for (const path of paths) {
      const schema = this.schemas[path];
      for (const dep of this.dependenciesOf(schema)) {
        if (!inDegree.has(dep)) {
          continue;
        }
        inDegree.set(path, (inDegree.get(path) ?? 0) + 1);
        dependents.get(dep)?.push(path);
      }
    }

    const ready = paths.filter((p) => (inDegree.get(p) ?? 0) === 0);

    const result: Schema[] = [];
    while (ready.length > 0) {
      ready.sort((a, b) => {
        const ka =
          this.constraintAliasNames[a] ?? this.getSchemaName(this.schemas[a]);
        const kb =
          this.constraintAliasNames[b] ?? this.getSchemaName(this.schemas[b]);
        return ka.localeCompare(kb) || a.localeCompare(b);
      });

      const next = ready.shift()!;
      result.push(this.schemas[next]);

      for (const dependent of dependents.get(next) ?? []) {
        const remaining = (inDegree.get(dependent) ?? 0) - 1;
        inDegree.set(dependent, remaining);
        if (remaining === 0) {
          ready.push(dependent);
        }
      }
    }

    if (result.length !== paths.length) {
      throw new Error('Cycle detected in model schema dependency graph.');
    }
    return result;
  }

  /**
   * Emits a single schema and returns the emitted block.
   */
  private emitSchema(schema: Schema): string {
    switch (schema.kind) {
      case 'enum':
        return this.emitEnum(schema);
      case 'union':
        return this.emitUnion(schema);
      case 'object':
        return this.emitObject(schema);
    }
  }

  /**
   * Emits the source for an enum schema.
   */
  private emitEnum(schema: EnumSchema): string {
    const name = this.getSchemaName(schema);
    this.generatedSchemas[schema.path] = { name, file: this.outputPath };

    const lines: string[] = [];
    lines.push(this.formatJsdoc(schema.description));
    lines.push(`export enum ${name} {`);
    const caseNames = this.enumCaseNames(schema);
    for (const [index, value] of schema.values.entries()) {
      const caseName = caseNames[index];
      lines.push(`  ${caseName} = ${JSON.stringify(value)},`);
    }
    lines.push('}');
    return lines.join('\n');
  }

  /**
   * Emits the source for a top-level union schema.
   */
  private emitUnion(schema: UnionSchema): string {
    const name = this.getSchemaName(schema);
    this.generatedSchemas[schema.path] = { name, file: this.outputPath };

    const members = schema.types
      .map((t) => this.sourceForPropertyType(t))
      .join(' | ');

    const lines: string[] = [];
    lines.push(this.formatJsdoc(schema.description));
    lines.push(`export type ${name} = ${members};`);
    return lines.join('\n');
  }

  /**
   * Emits the source for an object schema, including the constraint type alias when applicable.
   */
  private emitObject(schema: ObjectSchema): string {
    const constraintForPath = this.getBasePathForConstraintSchema(schema);
    const aliasName =
      constraintForPath !== undefined
        ? this.constraintAliasNames[schema.path]
        : null;
    const className = this.getSchemaName(schema);

    this.generatedSchemas[schema.path] = {
      name: aliasName ?? className,
      file: this.outputPath,
    };

    const lines: string[] = [];

    if (aliasName && constraintForPath !== undefined) {
      const baseSchema = this.schemas[constraintForPath];
      if (!baseSchema) {
        throw new Error(
          `Constraint '${className}' references unknown base schema '${constraintForPath}'.`,
        );
      }
      lines.push(this.formatJsdoc(schema.description));
      lines.push(
        `export type ${aliasName} = ${this.getSchemaName(baseSchema)} & ${className};`,
      );
      lines.push('');
    }

    lines.push(this.formatJsdoc(schema.description));

    const schemaDecorators = this.decorators[schema.path];
    const extClassDecorators = (schema.extensions.tsDecorators ??
      []) as TypeScriptDecorator[];
    for (const decorator of [
      ...extClassDecorators,
      ...(schemaDecorators?.class ?? []),
    ]) {
      this.addImports(decorator.imports);
      lines.push(decorator.source);
    }

    lines.push(`export class ${className} {`);
    lines.push(`constructor(init: ${className}) {`);
    lines.push(`Object.assign(this, init);`);
    lines.push(`}`);

    for (const property of schema.properties) {
      lines.push('');
      lines.push(...this.emitProperty(schema, property, schemaDecorators));
    }

    lines.push(`}`);

    return lines.join('\n');
  }

  /**
   * Emits the lines for a single property within a class, including its description, decorators and field declaration.
   */
  private emitProperty(
    schema: ObjectSchema,
    property: Property,
    schemaDecorators: ModelClassSchemaDecorators | undefined,
  ): string[] {
    const lines: string[] = [];
    lines.push(this.formatJsdoc(property.description));

    const extDecorators = (property.extensions.tsDecorators ??
      []) as TypeScriptDecorator[];
    for (const decorator of extDecorators) {
      this.addImports(decorator.imports);
      lines.push(decorator.source);
    }
    const propertyDecorators =
      schemaDecorators?.properties[property.name] ?? [];
    for (const decorator of propertyDecorators) {
      this.addImports(decorator.imports);
      lines.push(decorator.source);
    }

    const { tsType, tsDefault } = property.extensions;
    const typeSource =
      typeof tsType === 'string'
        ? tsType
        : this.sourceForProperty(schema, property);

    const marker = tsDefault ? '' : property.required ? '!' : '?';
    const assignment = tsDefault ? ` = ${tsDefault}` : '';
    const namePart = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(property.name)
      ? property.name
      : JSON.stringify(property.name);
    lines.push(`readonly ${namePart}${marker}: ${typeSource}${assignment};`);

    return lines;
  }

  /**
   * Returns the TypeScript type source for a property, applying the property-level nullability and `enumHint`.
   */
  private sourceForProperty(schema: ObjectSchema, property: Property): string {
    if (property.type.kind === 'const') {
      const constraintFor = this.getBasePathForConstraintSchema(schema);
      const baseSchema =
        constraintFor !== undefined ? this.schemas[constraintFor] : undefined;
      if (baseSchema?.kind === 'object') {
        const baseProperty = baseSchema.properties.find(
          (p) => p.name === property.name,
        );
        if (baseProperty?.type.kind === 'ref') {
          const baseEnum = this.schemas[baseProperty.type.ref];
          if (baseEnum?.kind === 'enum') {
            const constValue = property.type.value;
            const caseName =
              this.enumCaseNames(baseEnum)[
                baseEnum.values.findIndex((v) => v === constValue)
              ];
            if (caseName) {
              return `${this.getSchemaName(baseEnum)}.${caseName}`;
            }
          }
        }
      }
    }

    let base = this.sourceForPropertyType(property.type);

    const enumHint = property.extensions.enumHint;
    if (typeof enumHint === 'string') {
      const enumSchema = this.schemas[enumHint];
      if (enumSchema && enumSchema.kind === 'enum') {
        const enumName = this.getSchemaName(enumSchema);
        const existing = this.existingSchemas[enumHint];
        if (existing && existing.file !== this.outputPath) {
          this.addImports({ [existing.file]: [existing.name] });
        }
        if (property.type.kind === 'array') {
          const itemSource = this.sourceForPropertyType(property.type.items);
          const itemBase = property.type.itemNullable
            ? `${itemSource} | null`
            : itemSource;
          base = `(${itemBase} | ${enumName})[]`;
        } else {
          base = `${base} | ${enumName}`;
        }
      }
    }

    if (property.nullable) {
      base = `${base} | null`;
    }

    return base;
  }

  /**
   * Returns the TypeScript type source for a property type (without property-level nullability or enum hint applied).
   */
  private sourceForPropertyType(type: PropertyType): string {
    switch (type.kind) {
      case 'primitive':
        switch (type.type) {
          case 'string':
          case 'uuid':
            return 'string';
          case 'integer':
          case 'number':
            return 'number';
          case 'boolean':
            return 'boolean';
          case 'datetime':
            return 'Date';
        }
      case 'null':
        return 'null';
      case 'const':
        return JSON.stringify(type.value);
      case 'ref': {
        const existing = this.existingSchemas[type.ref];
        if (existing) {
          if (existing.file !== this.outputPath) {
            this.addImports({ [existing.file]: [existing.name] });
          }
          return existing.name;
        }
        const target = this.schemas[type.ref];
        if (!target) {
          throw new Error(`Unknown schema reference '${type.ref}'.`);
        }
        return this.getSchemaName(target);
      }
      case 'array': {
        const inner = this.sourceForPropertyType(type.items);
        const item = type.itemNullable ? `${inner} | null` : inner;
        return `(${item})[]`;
      }
      case 'map': {
        if (type.items === 'any') {
          return 'Record<string, any>';
        }
        return `Record<string, ${this.sourceForPropertyType(type.items)}>`;
      }
    }
  }

  /**
   * Merges the given imports into {@link imports}.
   */
  private addImports(imports: Record<string, string[]>): void {
    for (const [path, symbols] of Object.entries(imports)) {
      const existing = this.imports[path];
      if (existing) {
        for (const s of symbols) {
          existing.add(s);
        }
      } else {
        this.imports[path] = new Set(symbols);
      }
    }
  }

  /**
   * Emits the source for the collected imports, sorted: module specifiers first (alphabetically), then absolute paths
   * converted to relative `./...js` imports.
   */
  private emitImports(): string {
    const entries = Object.entries(this.imports);
    if (entries.length === 0) {
      return '';
    }

    const outputDir = dirname(this.outputPath);
    const sorted = entries
      .map(([path, symbols]) => {
        let specifier = path;
        if (path.startsWith('/')) {
          specifier = relative(outputDir, path);
          if (!specifier.startsWith('.')) {
            specifier = `./${specifier}`;
          }
          specifier = specifier.replace(/\.ts$/, '.js');
        }
        return { path, symbols, specifier };
      })
      .toSorted(
        (a, b) =>
          Number(a.path.startsWith('/')) - Number(b.path.startsWith('/')) ||
          a.specifier.localeCompare(b.specifier),
      );

    const lines: string[] = [];
    for (const { specifier, symbols } of sorted) {
      if (symbols.size === 0) {
        lines.push(`import '${specifier}';`);
        continue;
      }
      const symbolsList = [...symbols]
        .filter((s) => !s.startsWith('type ') || !symbols.has(s.slice(5)))
        .toSorted()
        .join(', ');
      lines.push(`import { ${symbolsList} } from '${specifier}';`);
    }
    return lines.join('\n');
  }

  /**
   * Returns the JSDoc block for a description, or an empty string when the description is empty.
   */
  private formatJsdoc(description: string | undefined): string {
    if (!description) {
      return '';
    }
    return [
      '/**',
      ...description
        .split('\n')
        .map((l) => l.trimEnd())
        .map((l) => ` * ${l}`),
      ' */',
    ].join('\n');
  }

  /**
   * Returns deduplicated, valid TypeScript enum case names for the given enum schema (preserving source order).
   */
  private enumCaseNames(schema: EnumSchema): string[] {
    const seen = new Map<string, number>();
    return schema.values.map((value) => {
      const base = pascalCase(
        typeof value === 'string' ? value : `const_${value}`,
      );
      const safe = /^[A-Za-z_$]/.test(base) ? base : `_${base}`;
      const count = seen.get(safe) ?? 0;
      seen.set(safe, count + 1);
      return count === 0 ? safe : `${safe}_${count + 1}`;
    });
  }
}
