import type {
  ArrayPropertyType,
  ConstPropertyType,
  EnumSchema,
  GeneratedSchemas,
  ObjectSchema,
  Property,
  PropertyType,
  RefPropertyType,
  Schema,
} from '@causa/workspace-core';
import { pascalCase } from 'change-case';
import { mkdir, writeFile } from 'fs/promises';
import { dirname, relative } from 'path';
import prettier from 'prettier';

/**
 * The leading comment for the generated file.
 */
const LEADING_COMMENT =
  'This file was generated by the Causa command line. Do not edit it manually.';

/**
 * The default suffix used to identify constraint classes (e.g. `FooConstraint`).
 */
const DEFAULT_CONSTRAINT_SUFFIX = 'Constraint';

/**
 * Options for {@link TypeScriptTestObjectGenerator}.
 */
export type TypeScriptTestObjectGeneratorOptions = Partial<
  Pick<TypeScriptTestObjectGenerator, 'constraintSuffix'>
>;

/**
 * Generates TypeScript `make*` factory functions for the given {@link Schema}s and writes the formatted output to
 * disk.
 *
 * Each object schema becomes a `make<ClassName>(data?: Partial<ClassName>): ClassName` function that constructs a
 * default instance suitable for tests. Enums and unions are not emitted (only their referenced types' make functions
 * use them). Constraint schemas (with `extensions.constraintFor`) instantiate the base class and cast to the
 * constraint type.
 */
export class TypeScriptTestObjectGenerator {
  /**
   * Schemas successfully emitted as `make*` functions, indexed by their source path.
   */
  readonly generatedSchemas: GeneratedSchemas = {};

  /**
   * Imports collected while emitting. Keys are module specifiers or absolute file paths; values are the symbols to
   * import.
   */
  private readonly imports: Record<string, Set<string>> = {};

  /**
   * The suffix used to identify constraint classes. Defaults to `Constraint`.
   */
  readonly constraintSuffix: string;

  /**
   * Creates a new generator.
   *
   * @param outputPath Absolute path of the file the rendered source will be written to.
   * @param schemas The schemas to render, indexed by their absolute source path. Should include every schema that the
   *   emitted functions can reach (objects to emit + every enum / object referenced from their properties), since the
   *   default-value emitter introspects them.
   * @param modelClassSchemas The output of the model-class generator, used to look up the class / enum name and the
   *   file each model-class symbol lives in.
   * @param options Options.
   */
  constructor(
    readonly outputPath: string,
    readonly schemas: Record<string, Schema>,
    readonly modelClassSchemas: GeneratedSchemas,
    readonly options: TypeScriptTestObjectGeneratorOptions = {},
  ) {
    this.constraintSuffix =
      options.constraintSuffix ?? DEFAULT_CONSTRAINT_SUFFIX;
  }

  /**
   * Renders all eligible schemas, formats the output with prettier, and writes it to {@link outputPath}.
   * Populates {@link generatedSchemas}.
   */
  async generate(): Promise<void> {
    const ordered = this.topologicalSort();

    const blocks: string[] = [];
    for (const schema of ordered) {
      blocks.push(this.emitMakeFunction(schema));
    }

    const lines = [
      ...LEADING_COMMENT.split('\n').map((l) => `// ${l}`),
      '',
      this.emitImports(),
      '',
      blocks.join('\n\n'),
    ];

    await this.writeFile(lines.join('\n'));
  }

  /**
   * Formats the given source code with `prettier` and writes it to {@link outputPath}, creating the parent directory
   * if needed.
   */
  private async writeFile(source: string): Promise<void> {
    const prettierConfig = await prettier.resolveConfig(this.outputPath);
    const formatted = await prettier.format(source, {
      parser: 'typescript',
      ...prettierConfig,
    });
    await mkdir(dirname(this.outputPath), { recursive: true });
    await writeFile(this.outputPath, formatted);
  }

  /**
   * Returns the object schemas this generator should emit `make*` functions for, topologically sorted so that
   * dependencies (nested objects) come first. Enums, unions, and constraint-only base schemas are skipped by the
   * emit loop, not by the sort.
   */
  private topologicalSort(): ObjectSchema[] {
    const objectPaths = Object.entries(this.schemas)
      .filter(([, s]) => s.kind === 'object')
      .map(([p]) => p);

    const inDegree = new Map<string, number>();
    const dependents = new Map<string, string[]>();
    for (const path of objectPaths) {
      inDegree.set(path, 0);
      dependents.set(path, []);
    }

    for (const path of objectPaths) {
      const schema = this.schemas[path] as ObjectSchema;
      const deps = new Set<string>();
      for (const property of schema.properties) {
        this.collectObjectRefs(property.type, deps);
      }
      for (const dep of deps) {
        if (!inDegree.has(dep) || dep === path) {
          continue;
        }
        inDegree.set(path, (inDegree.get(path) ?? 0) + 1);
        dependents.get(dep)?.push(path);
      }
    }

    const ready = objectPaths.filter((p) => (inDegree.get(p) ?? 0) === 0);
    const result: ObjectSchema[] = [];
    while (ready.length > 0) {
      ready.sort((a, b) => {
        const ka = this.modelClassSchemas[a]?.name ?? a;
        const kb = this.modelClassSchemas[b]?.name ?? b;
        return ka.localeCompare(kb) || a.localeCompare(b);
      });
      const next = ready.shift()!;
      result.push(this.schemas[next] as ObjectSchema);
      for (const dependent of dependents.get(next) ?? []) {
        const remaining = (inDegree.get(dependent) ?? 0) - 1;
        inDegree.set(dependent, remaining);
        if (remaining === 0) {
          ready.push(dependent);
        }
      }
    }

    return result;
  }

  /**
   * Recursively collects the paths of every object schema reachable from the given property type.
   */
  private collectObjectRefs(type: PropertyType, out: Set<string>): void {
    switch (type.kind) {
      case 'ref': {
        const target = this.schemas[type.ref];
        if (target?.kind === 'object') {
          out.add(type.ref);
        }
        return;
      }
      case 'array':
        this.collectObjectRefs(type.items, out);
        return;
      case 'map':
        if (type.items !== 'any') {
          this.collectObjectRefs(type.items, out);
        }
        return;
      default:
        return;
    }
  }

  /**
   * Emits the `make<Name>` function for a single object schema and records it in {@link generatedSchemas}.
   */
  private emitMakeFunction(schema: ObjectSchema): string {
    const constraintFor = schema.extensions.constraintFor;
    const isConstraint = typeof constraintFor === 'string';
    const modelClass = this.findModelClass(schema.path);
    const functionName = `make${this.factoryNameFor(schema)}`;

    let instantiationClassName: string;
    if (isConstraint) {
      const base = this.findModelClass(constraintFor);
      instantiationClassName = base.name;
      this.addImports({ [base.file]: [base.name] });
      this.addImports({ [modelClass.file]: [`type ${modelClass.name}`] });
    } else {
      instantiationClassName = modelClass.name;
      this.addImports({ [modelClass.file]: [modelClass.name] });
    }

    this.generatedSchemas[schema.path] = {
      name: functionName,
      file: this.outputPath,
    };

    return `export function ${functionName}(data: Partial<${modelClass.name}> = {}): ${modelClass.name} {
  return new ${instantiationClassName}({
    ${this.emitPropertyDefaults(schema)}
    ...data,
  })${isConstraint ? ` as ${modelClass.name}` : ''};
}`;
  }

  /**
   * Emits the property defaults for the given object schema. For a constraint schema, the constraint's own properties
   * are emitted first (alphabetically), followed by the base schema's remaining properties (also alphabetically).
   */
  private emitPropertyDefaults(schema: ObjectSchema): string {
    const constraintFor = schema.extensions.constraintFor;
    const baseSchema =
      typeof constraintFor === 'string'
        ? this.schemas[constraintFor]
        : undefined;
    const baseObject = baseSchema?.kind === 'object' ? baseSchema : undefined;

    const ownEntries = schema.properties
      .map((p) => [p.name, this.defaultValueForProperty(p, baseObject)])
      .sort(([a], [b]) => a.localeCompare(b));

    const ownNames = new Set(schema.properties.map((p) => p.name));
    const baseExtras = (baseObject?.properties ?? [])
      .filter((p) => !ownNames.has(p.name))
      .map((p) => [p.name, this.defaultValueForProperty(p)])
      .sort(([a], [b]) => a.localeCompare(b));

    return [...ownEntries, ...baseExtras]
      .map(
        ([name, source]) =>
          `${/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name)}: ${source},`,
      )
      .join('\n');
  }

  /**
   * Returns the TypeScript source for the default value of a property, applying the `testObjectDefaultValue` and
   * `enumHint` extensions where relevant.
   */
  private defaultValueForProperty(
    property: Property,
    baseSchema?: ObjectSchema,
  ): string {
    const serialized =
      property.extensions.testObjectDefaultValue !== undefined
        ? JSON.stringify(property.extensions.testObjectDefaultValue)
        : undefined;

    if (property.nullable && serialized === undefined) {
      return 'null';
    }

    const type = property.type;
    const kind = type.kind !== 'primitive' ? type.kind : type.type;
    switch (kind) {
      case 'null': {
        return 'null';
      }
      case 'const': {
        const constValue = (type as ConstPropertyType).value;
        const baseProperty = baseSchema?.properties.find(
          (p) => p.name === property.name,
        );
        if (baseProperty?.type.kind === 'ref') {
          const baseEnum = this.schemas[baseProperty.type.ref];
          if (baseEnum?.kind === 'enum') {
            const caseName = this.findEnumCaseName(baseEnum, constValue);
            if (caseName) {
              const modelClass = this.findModelClass(baseEnum.path);
              this.addImports({ [modelClass.file]: [modelClass.name] });
              return `${modelClass.name}.${caseName}`;
            }
          }
        }
        return JSON.stringify(constValue);
      }
      case 'array': {
        const arrayType = type as ArrayPropertyType;
        const itemRef =
          arrayType.items.kind === 'ref' ? arrayType.items.ref : undefined;
        const itemSchema = itemRef ? this.schemas[itemRef] : undefined;
        const defaultValues = property.extensions.testObjectDefaultValue;
        if (
          itemSchema?.kind === 'enum' &&
          Array.isArray(defaultValues) &&
          defaultValues.length > 0
        ) {
          const modelClass = this.findModelClass(itemSchema.path);
          this.addImports({ [modelClass.file]: [modelClass.name] });
          const entries = defaultValues.map((value) => {
            const caseName = this.findEnumCaseName(itemSchema, value);
            if (!caseName) {
              throw new Error(
                `Unknown enum value '${String(value)}' for property '${property.name}'.`,
              );
            }
            return `${modelClass.name}.${caseName}`;
          });
          return `[${entries.join(', ')}]`;
        }
        return serialized ?? '[]';
      }
      case 'map': {
        return serialized ?? '{}';
      }
      case 'ref': {
        const target = this.schemas[(type as RefPropertyType).ref];
        if (target?.kind === 'enum') {
          const value =
            property.extensions.testObjectDefaultValue ?? target.values[0];
          if (value === undefined) {
            throw new Error(
              `Enum '${target.name}' referenced from property '${property.name}' has no values.`,
            );
          }
          const caseName = this.findEnumCaseName(target, value);
          if (!caseName) {
            throw new Error(
              `Unknown enum value '${String(value)}' for property '${property.name}'.`,
            );
          }
          const modelClass = this.findModelClass(target.path);
          this.addImports({ [modelClass.file]: [modelClass.name] });
          return `${modelClass.name}.${caseName}`;
        }
        if (target?.kind === 'object') {
          return `make${this.factoryNameFor(target)}(${serialized ?? ''})`;
        }
        return serialized ?? "'unknown'";
      }
      case 'string': {
        if (serialized !== undefined) {
          return serialized;
        }
        const enumHint = property.extensions.enumHint;
        if (typeof enumHint === 'string') {
          const target = this.schemas[enumHint];
          if (target?.kind === 'enum' && target.values.length > 0) {
            return JSON.stringify(target.values[0]);
          }
        }
        return "'string'";
      }
      case 'integer': {
        return serialized ?? '0';
      }
      case 'number': {
        return serialized ?? '0.0';
      }
      case 'boolean': {
        return serialized ?? 'false';
      }
      case 'datetime': {
        return `new Date(${serialized ?? ''})`;
      }
      case 'uuid': {
        if (serialized !== undefined) {
          return serialized;
        }
        this.addImports({ crypto: ['randomUUID'] });
        return 'randomUUID()';
      }
    }
  }

  /**
   * Returns the PascalCase factory base name for the given object schema. Constraint schemas have their suffix
   * stripped so a `FooConstraint` schema becomes `makeFoo`.
   */
  private factoryNameFor(schema: ObjectSchema): string {
    const constraintFor = schema.extensions.constraintFor;
    const raw =
      typeof constraintFor === 'string' &&
      schema.name.endsWith(this.constraintSuffix)
        ? schema.name.slice(0, -this.constraintSuffix.length)
        : schema.name;
    return pascalCase(raw);
  }

  /**
   * Returns the {@link GeneratedSchemas} entry for the given schema path, or throws when the model-class output
   * does not cover it.
   */
  private findModelClass(path: string): { name: string; file: string } {
    const entry = this.modelClassSchemas[path];
    if (!entry) {
      throw new Error(
        `Schema '${path}' is not present in the model-class generator output.`,
      );
    }
    return entry;
  }

  /**
   * Returns the TypeScript enum case name corresponding to the given raw value, or `undefined` if the value is
   * absent from the enum.
   */
  private findEnumCaseName(
    schema: EnumSchema,
    value: unknown,
  ): string | undefined {
    const index = (schema.values as unknown[]).indexOf(value);
    if (index < 0) {
      return undefined;
    }
    return this.enumCaseNames(schema)[index];
  }

  /**
   * Returns deduplicated, valid TypeScript enum case names for the given enum schema (preserving source order).
   */
  private enumCaseNames(schema: EnumSchema): string[] {
    const seen = new Map<string, number>();
    return schema.values.map((value) => {
      const base = pascalCase(
        typeof value === 'string' ? value : `const_${value}`,
      );
      const safe = /^[A-Za-z_$]/.test(base) ? base : `_${base}`;
      const count = seen.get(safe) ?? 0;
      seen.set(safe, count + 1);
      return count === 0 ? safe : `${safe}_${count + 1}`;
    });
  }

  /**
   * Merges the given imports into {@link imports}.
   */
  private addImports(imports: Record<string, string[]>): void {
    for (const [path, symbols] of Object.entries(imports)) {
      const existing = this.imports[path];
      if (existing) {
        for (const s of symbols) {
          existing.add(s);
        }
      } else {
        this.imports[path] = new Set(symbols);
      }
    }
  }

  /**
   * Emits the source for the collected imports, sorted: module specifiers first (alphabetically), then absolute paths
   * converted to relative `./...js` imports.
   */
  private emitImports(): string {
    const entries = Object.entries(this.imports);
    if (entries.length === 0) {
      return '';
    }

    const outputDir = dirname(this.outputPath);
    const sorted = entries
      .map(([path, symbols]) => {
        let specifier = path;
        if (path.startsWith('/')) {
          specifier = relative(outputDir, path);
          if (!specifier.startsWith('.')) {
            specifier = `./${specifier}`;
          }
          specifier = specifier.replace(/\.ts$/, '.js');
        }
        return { path, symbols, specifier };
      })
      .toSorted(
        (a, b) =>
          Number(a.path.startsWith('/')) - Number(b.path.startsWith('/')) ||
          a.specifier.localeCompare(b.specifier),
      );

    const lines: string[] = [];
    for (const { specifier, symbols } of sorted) {
      if (symbols.size === 0) {
        lines.push(`import '${specifier}';`);
        continue;
      }
      const symbolsList = [...symbols]
        .filter((s) => !s.startsWith('type ') || !symbols.has(s.slice(5)))
        .toSorted()
        .join(', ');
      lines.push(`import { ${symbolsList} } from '${specifier}';`);
    }
    return lines.join('\n');
  }
}
