import type {
  ConstPropertyType,
  EventTopicDefinition,
  GeneratedSchema,
  GeneratedSchemas,
  ObjectSchema,
  PropertyType,
  RefPropertyType,
  Schema,
} from '@causa/workspace-core';
import { mkdir, writeFile } from 'fs/promises';
import micromatch from 'micromatch';
import { dirname, relative } from 'path';
import prettier from 'prettier';

/**
 * The leading comment for the generated file.
 */
const LEADING_COMMENT =
  'This file was generated by the Causa command line. Do not edit it manually.';

/**
 * The default suffix used to identify constraint classes (e.g. `FooConstraint`).
 */
const DEFAULT_CONSTRAINT_SUFFIX = 'Constraint';

/**
 * Options for {@link TypeScriptTestExpectationGenerator}.
 */
export type TypeScriptTestExpectationGeneratorOptions = Partial<
  Pick<TypeScriptTestExpectationGenerator, 'constraintSuffix' | 'entitiesGlobs'>
>;

/**
 * Generates TypeScript test expectation helper functions (`expect*`, `expectNo*`, `expect*NotMutated`,
 * `expect*NotToExist`) for the given {@link Schema}s and writes the formatted output to disk.
 *
 * The expectation kind for each object schema is decided as follows:
 * 1. If the schema's path matches an event topic, emit generic event expectations (`expect<X>`, `expectNo<X>`). If
 *    the schema also has the `entityEvent` extension, additionally emit `expect<EntityName>NotMutated`.
 * 2. Otherwise, if the schema has the `entityMutationFrom` extension (a mutation constraint), emit
 *    `expect<MutationName>` which exercises `VersionedEntityFixture.expectMutated`.
 * 3. Otherwise, if the schema's path matches `entitiesGlobs`, emit `expect<EntityName>` and (for non-constraint
 *    schemas) `expect<EntityName>NotToExist`.
 */
export class TypeScriptTestExpectationGenerator {
  /**
   * Schemas successfully emitted, indexed by their source path. The `name` field is a comma-separated list of every
   * function emitted for the schema (matching the legacy renderer behavior).
   */
  readonly generatedSchemas: GeneratedSchemas = {};

  /**
   * Imports collected while emitting.
   */
  private readonly imports: Record<string, Set<string>> = {};

  /**
   * The suffix used to identify constraint classes. Defaults to `Constraint`.
   */
  readonly constraintSuffix: string;

  /**
   * Absolute globs describing which schemas should generate entity expectations. When omitted, every schema not
   * matching a more specific case generates entity expectations.
   */
  readonly entitiesGlobs?: string[];

  /**
   * Creates a new generator.
   *
   * @param outputPath Absolute path of the file the rendered source will be written to.
   * @param schemas The schemas to introspect, indexed by their absolute source path. Should include every schema the
   *   emitted helpers can reach (objects to emit + every enum / union / object referenced from their properties).
   * @param modelClassSchemas The output of the model-class generator, used to look up class / enum names and import
   *   targets.
   * @param eventTopics Event topic definitions used to decide when to emit event-shaped expectations.
   * @param options Options.
   */
  constructor(
    readonly outputPath: string,
    readonly schemas: Record<string, Schema>,
    readonly modelClassSchemas: GeneratedSchemas,
    readonly eventTopics: EventTopicDefinition[],
    readonly options: TypeScriptTestExpectationGeneratorOptions = {},
  ) {
    this.constraintSuffix =
      options.constraintSuffix ?? DEFAULT_CONSTRAINT_SUFFIX;
    this.entitiesGlobs = options.entitiesGlobs;
  }

  /**
   * Renders every eligible schema, formats the output with prettier, and writes it to {@link outputPath}.
   * Populates {@link generatedSchemas}. Returns silently when nothing matches.
   */
  async generate(): Promise<void> {
    const blocks: string[] = [];

    const sortedSchemas = Object.values(this.schemas).toSorted((a, b) =>
      a.path.localeCompare(b.path),
    );
    for (const schema of sortedSchemas) {
      if (schema.kind !== 'object') {
        continue;
      }

      const names = this.emitExpectation(schema, blocks);
      if (names.length > 0) {
        this.generatedSchemas[schema.path] = {
          name: names.join(','),
          file: this.outputPath,
        };
      }
    }

    const lines = [
      ...LEADING_COMMENT.split('\n').map((l) => `// ${l}`),
      '',
      this.emitImports(),
      '',
      blocks.join('\n\n'),
    ];

    await this.writeFile(lines.join('\n'));
  }

  /**
   * Formats the given source code with `prettier` and writes it to {@link outputPath}, creating the parent directory
   * if needed.
   */
  private async writeFile(source: string): Promise<void> {
    await mkdir(dirname(this.outputPath), { recursive: true });
    const prettierConfig = await prettier.resolveConfig(this.outputPath);
    const formatted = await prettier.format(source, {
      parser: 'typescript',
      ...prettierConfig,
    });
    await writeFile(this.outputPath, formatted);
  }

  /**
   * Emits the relevant function block(s) for the given schema, appending the source to `blocks` and returning the
   * list of emitted function names. Picks the expectation kind from the schema (event topic match → entity event /
   * generic event; `entityMutationFrom` extension → entity mutation; matching `entitiesGlobs` → entity).
   */
  private emitExpectation(schema: ObjectSchema, blocks: string[]): string[] {
    const eventTopic = this.eventTopics.find(
      (t) => t.schemaFilePath === schema.path,
    );
    if (eventTopic) {
      const eventNames = this.emitGenericEventExpectations(
        schema,
        eventTopic,
        blocks,
      );
      if (!schema.extensions.entityEvent) {
        return eventNames;
      }

      const notMutatedNames = this.emitEntityEventNotMutated(
        schema,
        eventTopic,
        blocks,
      );
      return [...notMutatedNames, ...eventNames];
    }

    if (schema.extensions.entityMutationFrom) {
      return this.emitEntityMutated(schema, blocks);
    }

    if (
      !this.entitiesGlobs ||
      micromatch.isMatch(schema.path.split('#')[0], this.entitiesGlobs)
    ) {
      return this.emitEntityExpectation(schema, blocks);
    }

    return [];
  }

  /**
   * Emits `expect<X>` and (when not a constraint) `expect<X>NotToExist`.
   */
  private emitEntityExpectation(
    schema: ObjectSchema,
    blocks: string[],
  ): string[] {
    const constraintFor = schema.extensions.constraintFor;
    const isConstraint = typeof constraintFor === 'string';
    const expectationModelClass = this.findModelClass(schema.path);
    this.addImports({
      [expectationModelClass.file]: [
        isConstraint
          ? `type ${expectationModelClass.name}`
          : expectationModelClass.name,
      ],
    });

    let entityClassName = expectationModelClass.name;
    if (isConstraint) {
      const base = this.findModelClass(constraintFor);
      entityClassName = base.name;
      this.addImports({ [base.file]: [base.name] });
    }

    this.addImports({
      '@causa/runtime': [
        'type Transaction',
        'type TransactionRunner',
        'type ReadOnlyStateTransaction',
      ],
    });

    const existFunctionName = `expect${this.functionBaseName(schema)}`;
    blocks.push(`export async function ${existFunctionName}(
  runner: TransactionRunner<Transaction, ReadOnlyStateTransaction>,
  expected: Partial<${expectationModelClass.name}>,
): Promise<${expectationModelClass.name}> {
  const actual = await runner.run({ readOnly: true }, (t) => t.get(${entityClassName}, expected));
  expect(actual).toEqual({
    ${this.emitPropertyMatchers(schema)}
    ...expected,
  });
  return actual as ${expectationModelClass.name};
}`);

    const names = [existFunctionName];

    if (!isConstraint) {
      const notExistName = `${existFunctionName}NotToExist`;
      blocks.push(`export async function ${notExistName}(
  runner: TransactionRunner<Transaction, ReadOnlyStateTransaction>,
  key: Partial<${expectationModelClass.name}>,
): Promise<void> {
  const actual = await runner.run({ readOnly: true }, (t) => t.get(${entityClassName}, key));
  expect(actual).toEqual(null);
}`);
      names.push(notExistName);
    }

    return names;
  }

  /**
   * Emits the `expect<X>` + `expectNo<X>` event helpers for an event-topic-matching schema.
   */
  private emitGenericEventExpectations(
    schema: ObjectSchema,
    eventTopic: EventTopicDefinition,
    blocks: string[],
  ): string[] {
    const eventClass = this.findModelClass(schema.path);
    this.addImports({ [eventClass.file]: [eventClass.name] });
    this.addImports({
      '@causa/runtime/nestjs/testing': ['type EventFixture'],
    });

    const expectName = `expect${this.functionBaseName(schema)}`;
    const expectNoName = `expectNo${this.functionBaseName(schema)}`;

    blocks.push(`export async function ${expectName}(
  eventFixture: EventFixture,
  expected: Partial<${eventClass.name}> = {},
): Promise<void> {
  await eventFixture.expectEvent(${JSON.stringify(eventTopic.id)}, {
    ${this.emitPropertyMatchers(schema)}
    ...expected,
  });
}`);
    blocks.push(`export async function ${expectNoName}(
  eventFixture: EventFixture,
): Promise<void> {
  await eventFixture.expectNoEvent(${JSON.stringify(eventTopic.id)});
}`);

    return [expectName, expectNoName];
  }

  /**
   * Emits `expect<EntityName>NotMutated` for an entity event topic schema.
   */
  private emitEntityEventNotMutated(
    schema: ObjectSchema,
    eventTopic: EventTopicDefinition,
    blocks: string[],
  ): string[] {
    const dataObject = this.eventDataObject(schema);
    const entityClass = this.findModelClass(dataObject.path);
    this.addImports({ [entityClass.file]: [entityClass.name] });
    this.addImports({
      '@causa/runtime/testing': ['VersionedEntityFixture'],
      '@causa/runtime/nestjs/testing': ['type AppFixture'],
    });

    const functionName = `expect${this.functionBaseName(dataObject)}NotMutated`;
    blocks.push(`export async function ${functionName}(
  fixture: AppFixture,
  entity: ${entityClass.name},
  tests: { expectNoEvent?: boolean } = {},
): Promise<void> {
  await fixture.get(VersionedEntityFixture).expectNoMutation(entity, {
    expectNoEventInTopic: tests.expectNoEvent ? ${JSON.stringify(eventTopic.id)} : undefined,
  });
}`);

    return [functionName];
  }

  /**
   * Emits `expect<MutationName>` for a mutation constraint schema (one with `entityMutationFrom` extension).
   */
  private emitEntityMutated(schema: ObjectSchema, blocks: string[]): string[] {
    const baseEventPath = schema.extensions.constraintFor;
    if (typeof baseEventPath !== 'string') {
      throw new Error(
        `Entity mutation '${schema.name}' must constrain a parent event schema.`,
      );
    }

    const baseEvent = this.schemas[baseEventPath];
    if (baseEvent?.kind !== 'object') {
      throw new Error(
        `Entity mutation '${schema.name}' constrains '${baseEventPath}' which is not an object schema.`,
      );
    }

    const eventTopic = this.eventTopics.find(
      (t) => t.schemaFilePath === baseEvent.path,
    );
    if (!eventTopic) {
      throw new Error(
        `Entity mutation '${schema.name}' constrains a schema that is not an event topic.`,
      );
    }

    const entityObject = this.eventDataObject(baseEvent);
    const constrainedEntityObject = this.eventDataObject(schema, baseEvent);

    const entityClass = this.findModelClass(entityObject.path);
    const constrainedEntityClass = this.findModelClass(
      constrainedEntityObject.path,
    );
    const isConstrainedEntity =
      typeof constrainedEntityObject.extensions.constraintFor === 'string';

    this.addImports({
      [constrainedEntityClass.file]: [
        isConstrainedEntity
          ? `type ${constrainedEntityClass.name}`
          : constrainedEntityClass.name,
      ],
    });
    this.addImports({ [entityClass.file]: [entityClass.name] });

    const eventNameProperty =
      schema.properties.find((p) => p.name === 'name') ??
      baseEvent.properties.find((p) => p.name === 'name');
    if (!eventNameProperty) {
      throw new Error(
        `Entity mutation '${schema.name}' or its parent must declare an event 'name' property.`,
      );
    }
    let eventNames: readonly unknown[] = [];
    if (eventNameProperty.type.kind === 'const') {
      eventNames = [eventNameProperty.type.value];
    } else if (eventNameProperty.type.kind === 'ref') {
      const target = this.schemas[eventNameProperty.type.ref];
      if (target?.kind === 'enum') {
        eventNames = target.values;
      }
    }
    if (eventNames.length === 0) {
      throw new Error(
        `Entity mutation '${schema.name}' has no event names to match.`,
      );
    }

    this.addImports({
      'jest-extended': [],
      '@causa/runtime': ['type EventAttributes'],
      '@causa/runtime/testing': ['VersionedEntityFixture'],
      '@causa/runtime/nestjs/testing': ['type AppFixture'],
    });

    const functionName = `expect${this.functionBaseName(schema)}`;
    const eventNameMatcher = `expect.toBeOneOf(${JSON.stringify(eventNames)})`;
    const entityMatchers = this.emitExpectedEntityMatchers(
      constrainedEntityObject,
      schema.extensions.entityPropertyChanges as string[] | '*' | undefined,
    );

    blocks.push(`export async function ${functionName}(
  fixture: AppFixture,
  before: Partial<${entityClass.name}>,
  updates: Partial<${constrainedEntityClass.name}> = {},
  tests: {
    matchesHttpResponse?: object;
    eventAttributes?: EventAttributes;
  } = {},
): Promise<${entityClass.name}> {
  return await fixture.get(VersionedEntityFixture).expectMutated(
    { type: ${entityClass.name}, entity: before },
    {
      expectedEntity: {
        ${entityMatchers}
      },
      expectedEvent: {
        topic: ${JSON.stringify(eventTopic.id)},
        name: ${eventNameMatcher},
        attributes: tests.eventAttributes,
      },
      matchesHttpResponse: tests.matchesHttpResponse,
    },
  );
}`);

    return [functionName];
  }

  /**
   * Returns the source for the `expectedEntity` block of an entity mutation expectation, interleaving `before` and
   * `updates` spreads with the property matchers as dictated by `entityPropertyChanges`.
   */
  private emitExpectedEntityMatchers(
    entityObject: ObjectSchema,
    changes: string[] | '*' | undefined,
  ): string {
    if (changes === '*') {
      return `${this.emitPropertyMatchers(entityObject)}\n...updates,`;
    }

    const set = new Set(changes ?? []);
    return `${this.emitPropertyMatchers(entityObject, (n) => !set.has(n))}
...before,
${this.emitPropertyMatchers(entityObject, (n) => set.has(n))}
...updates,`;
  }

  /**
   * Returns the object schema reached by the `data` property of the given event object schema, falling back to the
   * `baseSchema`'s `data` property when the constraint omits it.
   */
  private eventDataObject(
    schema: ObjectSchema,
    baseSchema?: ObjectSchema,
  ): ObjectSchema {
    const dataProperty =
      schema.properties.find((p) => p.name === 'data') ??
      baseSchema?.properties.find((p) => p.name === 'data');
    if (dataProperty?.type.kind !== 'ref') {
      throw new Error(
        `Entity event '${schema.name}' must have a 'data' object property.`,
      );
    }

    const target = this.schemas[dataProperty.type.ref];
    if (target?.kind !== 'object') {
      throw new Error(
        `Entity event '${schema.name}' 'data' property must reference an object schema.`,
      );
    }

    return target;
  }

  /**
   * Returns the property matcher lines for a given object schema. Constraint own-properties are emitted first
   * (alphabetically), then any extra base properties (also alphabetically).
   *
   * @param schema The object schema to introspect.
   * @param filter Optional predicate; properties for which it returns `false` are skipped.
   */
  private emitPropertyMatchers(
    schema: ObjectSchema,
    filter: (name: string) => boolean = () => true,
  ): string {
    const constraintFor = schema.extensions.constraintFor;
    const baseSchema =
      typeof constraintFor === 'string'
        ? this.schemas[constraintFor]
        : undefined;
    const baseObject = baseSchema?.kind === 'object' ? baseSchema : undefined;

    const own = schema.properties
      .filter((p) => filter(p.name))
      .map((p) => [p.name, this.matcherForType(p.type, p)])
      .sort(([a], [b]) => a.localeCompare(b));

    const ownNames = new Set(schema.properties.map((p) => p.name));
    const baseExtras =
      baseObject?.properties
        .filter((p) => !ownNames.has(p.name) && filter(p.name))
        .map((p) => [p.name, this.matcherForType(p.type, p)])
        .sort(([a], [b]) => a.localeCompare(b)) ?? [];

    return [...own, ...baseExtras]
      .map(
        ([name, matcher]) =>
          `${/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name)}: ${matcher},`,
      )
      .join('\n');
  }

  /**
   * Returns the Jest matcher source for a given property type, with optional `null` / `undefined` allowed.
   */
  private matcherForType(
    type: PropertyType,
    options: { nullable?: boolean; required?: boolean } = {},
  ): string {
    this.addImports({ 'jest-extended': [] });

    const items: string[] = [];
    if (options.required === false) {
      items.push('undefined');
    }
    if (options.nullable) {
      items.push('null');
    }

    const kind = type.kind !== 'primitive' ? type.kind : type.type;
    switch (kind) {
      case 'null': {
        if (!items.includes('null')) {
          items.push('null');
        }
        break;
      }
      case 'const': {
        items.push(JSON.stringify((type as ConstPropertyType).value));
        break;
      }
      case 'ref': {
        const target = this.schemas[(type as RefPropertyType).ref];
        if (!target) {
          return 'expect.anything()';
        }

        if (target.kind === 'enum') {
          items.push(...target.values.map((v) => JSON.stringify(v)));
        } else if (target.kind === 'union') {
          items.push(...target.types.map((t) => this.matcherForType(t)));
        } else {
          const constraintFor = target.extensions.constraintFor;
          const base =
            typeof constraintFor === 'string'
              ? this.schemas[constraintFor]
              : undefined;
          const resolvedTarget = base?.kind === 'object' ? base : target;
          const modelClass = this.findModelClass(resolvedTarget.path);
          this.addImports({ [modelClass.file]: [modelClass.name] });
          items.push(`expect.any(${modelClass.name})`);
        }
        break;
      }
      case 'array': {
        items.push('expect.any(Array)');
        break;
      }
      case 'map': {
        items.push('expect.any(Object)');
        break;
      }
      case 'string':
      case 'uuid': {
        items.push('expect.any(String)');
        break;
      }
      case 'integer':
      case 'number': {
        items.push('expect.any(Number)');
        break;
      }
      case 'boolean': {
        items.push('expect.any(Boolean)');
        break;
      }
      case 'datetime': {
        items.push('expect.any(Date)');
        break;
      }
    }

    return items.length === 1
      ? items[0]
      : `expect.toBeOneOf([${items.join(', ')}])`;
  }

  /**
   * Returns the PascalCase base name used to build expectation function names (e.g. `expect<X>`). Constraint
   * schemas have their suffix stripped so a `FooConstraint` becomes `expectFoo`.
   */
  private functionBaseName(schema: ObjectSchema): string {
    const constraintFor = schema.extensions.constraintFor;
    return typeof constraintFor === 'string' &&
      schema.name.endsWith(this.constraintSuffix)
      ? schema.name.slice(0, -this.constraintSuffix.length)
      : schema.name;
  }

  /**
   * Returns the {@link GeneratedSchemas} entry for the given schema path, or throws when the model-class output
   * does not cover it.
   */
  private findModelClass(path: string): GeneratedSchema {
    const entry = this.modelClassSchemas[path];
    if (!entry) {
      throw new Error(
        `Schema '${path}' is not present in the model-class generator output.`,
      );
    }
    return entry;
  }

  /**
   * Merges the given imports into {@link imports}.
   */
  private addImports(imports: Record<string, string[]>): void {
    for (const [path, symbols] of Object.entries(imports)) {
      const existing = this.imports[path];
      if (existing) {
        for (const s of symbols) {
          existing.add(s);
        }
      } else {
        this.imports[path] = new Set(symbols);
      }
    }
  }

  /**
   * Emits the source for the collected imports, sorted: module specifiers first (alphabetically), then absolute
   * paths converted to relative `./...js` imports.
   */
  private emitImports(): string {
    const entries = Object.entries(this.imports);
    if (entries.length === 0) {
      return '';
    }

    const outputDir = dirname(this.outputPath);
    const sorted = entries
      .map(([path, symbols]) => {
        let specifier = path;
        if (path.startsWith('/')) {
          specifier = relative(outputDir, path);
          if (!specifier.startsWith('.')) {
            specifier = `./${specifier}`;
          }
          specifier = specifier.replace(/\.ts$/, '.js');
        }
        return { path, symbols, specifier };
      })
      .toSorted(
        (a, b) =>
          Number(a.path.startsWith('/')) - Number(b.path.startsWith('/')) ||
          a.specifier.localeCompare(b.specifier),
      );

    const lines: string[] = [];
    for (const { specifier, symbols } of sorted) {
      if (symbols.size === 0) {
        lines.push(`import '${specifier}';`);
        continue;
      }
      const symbolsList = [...symbols]
        .filter((s) => !s.startsWith('type ') || !symbols.has(s.slice(5)))
        .toSorted()
        .join(', ');
      lines.push(`import { ${symbolsList} } from '${specifier}';`);
    }
    return lines.join('\n');
  }
}
